apiVersion: v1
kind: Secret
metadata:
  name: {{ include "samplewebsite.fullname" . }}
  labels:
    {{- include "samplewebsite.labels" . | nindent 4 }}
type: Opaque
data:
  APP_CONFIG_CONNECTION: Endpoint=https://jkappconfig.azconfig.io;Id=Hyv5;Secret=ZafIQdMgZVdeozZjBkM3LhDz+bi8A6lmv+zx8j/a/6E=