apiVersion: v1
kind: Secret
metadata:
  name: {{ include "samplewebsite.fullname" . }}
  labels:
    {{- include "samplewebsite.labels" . | nindent 4 }}
type: Opaque
data:
  APP_CONFIG_CONNECTION: RW5kcG9pbnQ9aHR0cHM6Ly9qa2FwcGNvbmZpZy5hemNvbmZpZy5pbw== 